openapi: 3.0.0
info:
  title: "Travel Destination Vaccines REST API"
  description: "An API about vaccines for travel destinations"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /destinations/{country}/vaccines:
    get:
      operationId: "service.TravelDestinationVaccineService.getVaccines"
      tags:
        - "Destinations"
      summary: "Reads the list of vaccines for {country}"
      parameters:
        - $ref: "#/components/parameters/country"
      responses:
        "200":
          description: "Successfully read vaccines list"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VaccineList"
        "404":
          description: "Country with the specified name not found"
  /vaccines/{vaccine}/dosages:
    get:
      operationId: service.VaccineDosageService.getDosages
      tags:
        - "Vaccines"
      summary: "Reads the list of dosages for {vaccine}"
      parameters:
        - $ref: "#/components/parameters/vaccine"
        - $ref: "#/components/parameters/dateOfBirth"
      responses:
        "200":
          description: "Successfully read dosages list"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DosageList"
        "404":
          description: "Vaccine with the specified name not found"

components:
  parameters:
    country:
      name: country
      in: path
      schema:
        type: string
        example: brazil
      required: true
      description: "Name of the country to get"
    vaccine:
      name: vaccine
      in: path
      schema:
        type: string
        example: hepatitis-b
      required: true
      description: "Name of the vaccine to get"
    dateOfBirth:
      name: dateOfBirth
      in: query
      schema:
        type: string
        format: date
        example: 2000-03-31
      description: "Patient's date of birth"
  schemas:
    Vaccine:
      type: object
      properties:
        disease:
          type: string
          description: The name of the disease/illness to get a vaccine for.
          example: Yellow Fever
        recommendations:
          type: string
          description: Recommendations for the vaccine in the given country provided by the CDC website.
          example: |
            Recommended for all travelers ≥9 months of age going to the following areas: the entire states of Acre, Amapá, Amazonas, Distrito Federal (including the capital city of Brasília), Espirito Santo,* Goiás, Maranhão, Mato Grosso, Mato Grosso do Sul, Minas Gerais, Pará, Paraná,* Rio de Janeiro (including the city of Rio de Janeiro and all coastal islands),* Rio Grande do Sul,* Rondônia, Roraima, Santa Catarina,* São Paulo (including the city of São Paulo and all coastal islands),* and Tocantins and designated areas (see map) of the following states: Bahia* and Piauí. Vaccination is also recommended for travelers visiting Iguaçu Falls. Not recommended for travelers whose itineraries are limited to areas not listed above, including the cities of Fortaleza and Recife (see map). *Note: In 2017, CDC expanded YF vaccination recommendations for travelers to Brazil in response to a large YF outbreak in multiple eastern states. The expanded YF vaccination recommendations for these states are provisional.
    VaccineList:
      type: object
      properties:
        link:
          type: string
          format: uri
          description: A link to the country's CDC travel destination webpage.
          example: https://wwwnc.cdc.gov/travel/destinations/traveler/none/brazil
        vaccines:
          type: array
          items:
            $ref: "#/components/schemas/Vaccine"
    Dosage:
      type: object
      properties:
        genericName:
          type: string
          description: The name of the active ingredient.
          example: "Hepatitis A vaccine, inactivated"
        brandName:
          type: string
          description: The brand name of the vaccine.
          example: "Avaxim"
        minAge:
          $ref: "#/components/schemas/Age"
          description: The minimum age (years) a person should be for the dosage.
        maxAge:
          $ref: "#/components/schemas/Age"
          description: The maximum age (years) a person should be for the dosage.
        dose:
          $ref: "#/components/schemas/Dose"
          description: The amount of a medication to take at one specific time.
        numberOfDoses:
          type: integer
          description: The number of total doses a patient needs to take.
          example: 3
        schedule:
          type: string
          description: The schedule to take the dosage.
          example: "0, 8d+, 15d+"
    DosageList:
      type: object
      properties:
        dosages:
          type: array
          items:
            $ref: "#/components/schemas/Dosage"
    Age:
      type: object
      properties:
        value:
          type: integer
          example: 18
          description: Value of the age.
        unit:
          type: string
          enum: [months, years]
          example: years
          description: Unit of measurement for the age.
    Dose:
      type: object
      properties:
        value:
          type: number
          example: 1.5
          description: Amount of the dose.
        unit:
          type: string
          enum: [ml, mg, tablet]
          example: ml
          description: Unit of measurement in metric mass units.
